# proj setting
project: 'CMIL'
exp_name: 'csc_transmil_cl'
wandb_mode: 'disabled' # 'online', 'offline', 'disabled'

# model setting
model: transmil 
net: 'transmil'
D_feat: 512
L: 512
feature_extractor: null

# dataset setting
dataset: 'csc_cl'
data_root: '/root/cmil/MICIL-main/local_data'
feat_dir: 'embeddings'
classes_order: ['2', '4', '0', '5', '3', '1']
n_folds: 1
n_classes: 6
n_tasks: 3 # 2, 3, 5

# train setting
batch_size: 1
weighted_sample: False
n_batches: -1
early_stop: True
patience: 10
opt: adam
lr: [1e-5, 1e-6, 1e-6, 1e-6, 1e-6] # float or list
weight_decay: 0.
seed: 1
epochs: [20, 40, 25] # int or list
testing: False
load: null
debug: 'False' # False, lite/True (quick check), full (run a few steps)
folds_start: -1
folds_end: -1

# cl setting
cl_method: 'none' # 'none', 'finetune', 'ewc', 'replay', 'full-replay', 'joint'
buffer_size: -1 # 84
buffer_balance: False
buffer_slide_size: -1 # n_patches in a pseudo slide
distill_method: 'A' # 'topA', 'random'
wn: False # normalize fc weights
cl_on_current: False