D: 256
D_feat: 512
K: 1
L: 512
bag_weight: 0.7
batch_size: 1
bcsr_beta: 0.1
bcsr_lr_proxy_model: 5
bcsr_max_inner_it: 1
bcsr_max_outer_it: 3
bcsr_weight_lr: 10
buffer_balance: false
buffer_size: 42
buffer_slide_size: 200
cl_method: prev
cl_on_current: false
classes_order:
- '2'
- '4'
- '0'
- '5'
- '3'
- '1'
data_root: /mnt/nfs/zhangjinouwen/tangjia/cmil/bilevel-cmil/data
dataset: csc_cl
debug: false
distall_lamda: 0.1
distill_method: mix
draw_curve: false
dropout: true
early_stop: false
epochs:
- 40
- 50
- 50
exp_name: csc_clam_cl
feat_dir: embeddings
feature_extractor: null
folds_end: 1
folds_start: 0
gate: true
instance_loss_name: svm
k_sample: 8
load: null
log_dir: ckpt
lr:
- 1e-4
- 1e-4
- 1e-4
- 1e-4
- 1e-4
mix_coarse_ratio: 2.0
model: clam_sb
n_batches: -1
n_classes: 6
n_folds: 1
n_tasks: 2
net: clam_sb
opt: adam
patience: 10
preset: configs/csc_clam_cl.yaml
project: CMIL
seed: 1
subtyping: true
testing: false
wandb_mode: disabled
weight_decay: 0.0
weighted_sample: false
wn: false
